remote: true

experienceLevel:
  internship: false
  entry: false
  associate: false
  mid-senior level: true
  director: true
  executive: true

jobTypes:
  full-time: true
  contract: false
  part-time: false
  temporary: false
  internship: false
  other: false
  volunteer: false

date:
  all time: false
  month: false
  week: false
  24 hours: true

positions:
  - Director of Lifecycle Marketing
  - Head of Retention
  - Senior Lifecycle Marketing Manager
  - VP of Customer Retention
  - Product Marketing Manager
  - Product Marketing Lead

locations:
  - United States

apply_once_at_company: true

#distance: 100

company_blacklist:
  #- wayfair
  #- Crossover

title_blacklist:
  #- word1
 # - word2

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 100

llm_model_type: openai
llm_model: 'gpt-4o-mini'
# llm_api_url: https://api.pawan.krd/cosmosrp/v1'
